#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "-----------git提交信息校验-----------"
echo "ⓘ   提交规范: 遵循Conventional Commits规范。"
echo "ⓘ   规范详情: https://www.conventionalcommits.org/zh-hans/v1.0.0/"

npx --no -- commitlint --edit ${1}
